SPRING_DATA_MONGODB_INETADDRESS: mongodb://localhost:27017
SPRING_DATA_MONGODB_PORT: 27017
SPRING_DATA_MONGODB_DATABASE: Sportradar
SPRING_APPLICATION_NAME: sportradar
SPRING_MATCHING_STRATEGY: ant_path_matcher
JWT_SECRET: secretkey
SERVER_PORT: 9090

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    mongodb:
      database: ${SPRING_DATA_MONGODB_DATABASE}
      inetAddresses: ${SPRING_DATA_MONGODB_INETADDRESS}
      authenticationDatabase: admin
      port: ${SPRING_DATA_MONGODB_PORT}
  mvc:
    pathmatch:
      matching-strategy: ${SPRING_MATCHING_STRATEGY}

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT}
